//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCReleaseManagementProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class project_modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project_modules()
        {
            this.bugs = new HashSet<bug>();
        }

       [Required]
        [Display(Name = "Project Id")]
        public Nullable<int> projectid { get; set; }
        [Required]
        [RegularExpression("[a-zA-Z ]+")]
        [Display(Name = "Module Name")]
        public string name { get; set; }
        [Required]
        [RegularExpression("[0-9]+")]
        public int id { get; set; }
        [Required]
        [Display(Name = "Expected Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> e_start_date { get; set; }
        [Required]
        [Display(Name = "Expected End Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> e_end_date { get; set; }
        [Required]
        [Display(Name = "Actual Start Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> a_start_date { get; set; }
        [Required]
        [Display(Name = "Actual End Date")]
        [DataType(DataType.Date)]

        public Nullable<System.DateTime> a_end_date { get; set; }
        [Required]
        [Display(Name = "Developer")]

        public string developer { get; set; }
        [Required]
        [Display(Name = "Tester")]

        public string tester { get; set; }
        [Required]
        [Display(Name = "Module Status")]

        public string module_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bug> bugs { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual project project { get; set; }
    }
}
