//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCReleaseManagementProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class releaseProjectEntities : DbContext
    {
        public releaseProjectEntities()
            : base("name=releaseProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bug> bugs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LogIn> LogIns { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<project_modules> project_modules { get; set; }

        public System.Data.Entity.DbSet<MVCReleaseManagementProject.Models.projectViewModel> projectViewModels { get; set; }

        public System.Data.Entity.DbSet<MVCReleaseManagementProject.Models.moduleViewModel> moduleViewModels { get; set; }
    }
}
